services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mongo
      - rabbitmq
      - products
      - customer
      - shopping
    restart: always
    container_name: gm_nginx

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    container_name: gm_mongo

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    container_name: gm_rabbitmq

  products:
    image: ghcr.io/crunchydeer30/gm_products
    build:
      dockerfile: Dockerfile
      context: ./products
    env_file:
      - .env
    environment:
      PORT: ${PRODUCTS_PORT}
    ports:
      - ${PRODUCTS_PORT}:${PRODUCTS_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    container_name: gm_products

  customer:
    image: ghcr.io/crunchydeer30/gm_customer
    build:
      dockerfile: Dockerfile
      context: ./customer
    env_file:
      - .env
    environment:
      PORT: ${CUSTOMER_PORT}
    ports:
      - ${CUSTOMER_PORT}:${CUSTOMER_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    container_name: gm_customer

  shopping:
    image: ghcr.io/crunchydeer30/gm_shoppinga
    build:
      dockerfile: Dockerfile
      context: ./shopping
    env_file:
      - .env
    environment:
      PORT: ${SHOPPING_PORT}
    ports:
      - ${SHOPPING_PORT}:${SHOPPING_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    container_name: gm_shopping
