services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mongo
      - rabbitmq
      - products
      - customer
      - shopping
    container_name: gm_nginx

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/:/data/db
    container_name: gm_mongo

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 2s
      retries: 5
    container_name: gm_rabbitmq

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    ports:
      - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: gm_products

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: gm_customer

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    ports:
      - "8003:8003"
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: gm_shopping
