name: Build Docker images

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: "shopping:meta"
        id: shopping-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/crunchydeer30/gm_test_shopping
          tags: |
            type=semver,pattern={{version}}

      - name: shoping:build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:shopping"
          tags: ${{steps.shopping-meta.outputs.tags}}
          labels: ${{steps.shopping-meta.outputs.labels}}
