on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/${{ github.repository }}:latest

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_PROD }}" > .env
          cat .env
      - name: login
        run: |
          echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker compose build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker compose push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
