on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
# on:
#   push:
#     branches:
#       - main
# #
# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#       contents: write
#     steps:
#       - uses: google-github-actions/release-please-action@v4
#         with:
#           release-type: simple
#           token: ${{ secrets.PAT }}
